-- 테이블 생성
CREATE TABLE NETFLIX (
	
	VIDEO_NAME		VARCHAR2(50),
	CATEGORY		VARCHAR2(30),
	VIEW_CNT		NUMBER(7),
	REG_DATE		DATE
	
);

SELECT * FROM NETFLIX;

-- 새로운 컬럼 추가 
ALTER TABLE NETFLIX ADD (CAST_MEMBER VARCHAR2(20));

-- 컬럼 크기 변경 
ALTER TABLE NETFLIX MODIFY (CAST_MEMBER VARCHAR2(50));

-- 컬럼 데이터 타입 변경 
ALTER TABLE NETFLIX MODIFY (CAST_MEMBER NUMBER(2));

-- 컬럼 삭제
ALTER TABLE NETFLIX DROP (CAST_MEMBER);

-- 테스트 테이블 생성
CREATE TABLE CODELION (

	COL1	VARCHAR2(3),
	COL2	VARCHAR2(3)

);

SELECT * FROM CODELION;

INSERT INTO CODELION VALUES ('AAA', 'BBB');
INSERT INTO CODELION VALUES ('CCC', 'DDD');

COMMIT;

-- 데이터와 테이블 모두 삭제 
DROP TABLE CODELION;

-- 데이터만 삭제 후 빈 테이블 유지
TRUNCATE TABLE CODELION;

