SELECT * FROM STARBUCKS_ORDER;

SELECT ORDER_DT, COUNT(*) AS CNT
  FROM STARBUCKS_ORDER
GROUP BY ORDER_DT
ORDER BY ORDER_DT;
 
-- CUBE 함수: 총 합계
SELECT ORDER_DT, COUNT(*) AS CNT
  FROM STARBUCKS_ORDER
GROUP BY CUBE(ORDER_DT)
ORDER BY ORDER_DT;

-- GROUP BY ORDER_DT, ORDER_ITEM
-- + GROUP BY ORDER_DT
-- + GROUP BY ORDER_ITEM
-- + 총 합계
SELECT ORDER_DT, ORDER_ITEM, COUNT(*) AS CNT
  FROM STARBUCKS_ORDER
GROUP BY CUBE(ORDER_DT, ORDER_ITEM)
ORDER BY ORDER_DT;

-- 위와 동일한 결과 출력 (ROLLUP과 달리 컬럼의 순서 영향 없음)
SELECT ORDER_DT, ORDER_ITEM, COUNT(*) AS CNT
  FROM STARBUCKS_ORDER
GROUP BY CUBE(ORDER_ITEM, ORDER_DT)
ORDER BY ORDER_DT;

-- CUBE 함수를 풀어서 쓴 쿼리
SELECT ORDER_DT, ORDER_ITEM, COUNT(*) AS CNT -- GROUP BY ORDER_DT, ORDER_ITEM
  FROM STARBUCKS_ORDER
GROUP BY ORDER_ITEM, ORDER_DT
UNION ALL
SELECT ORDER_DT, NULL, COUNT(*) -- GROUP BY ORDER_DT
  FROM STARBUCKS_ORDER
GROUP BY ORDER_DT
UNION ALL
SELECT NULL, ORDER_ITEM, COUNT(*) -- GROUP BY ORDER_ITEM
  FROM STARBUCKS_ORDER
GROUP BY ORDER_ITEM
UNION ALL
SELECT NULL, NULL, COUNT(*) -- 총 합계
  FROM STARBUCKS_ORDER
ORDER BY 1, 2; -- 1번째 컬럼과 2번째 컬럼을 기준으로 오름차순 정리
