-- PARENT 테이블 생성
CREATE TABLE PRACTICE.PARENT (
    P_ID    VARCHAR2(2) NOT NULL
);

-- PK 지정
ALTER TABLE PRACTICE.PARENT ADD CONSTRAINT P_PK PRIMARY KEY(P_ID);

CREATE TABLE PRACTICE.CHILD (
    C_ID    VARCHAR2(2) NOT NULL,
    P_ID    VARCHAR2(2)
);

-- PK 지정
ALTER TABLE PRACTICE.CHILD ADD CONSTRAINT C_PK PRIMARY KEY(C_ID);

-- FK 지정
ALTER TABLE PRACTICE.CHILD ADD CONSTRAINT C_FK FOREIGN KEY(P_ID) REFERENCES PRACTICE.PARENT(P_ID); 

-- 데이터 INSERT
INSERT INTO PRACTICE.PARENT VALUES ('A');
SELECT * FROM PRACTICE.PARENT;

INSERT INTO PRACTICE.CHILD VALUES ('a', 'A');
SELECT * FROM PRACTICE.CHILD;

-- 에러 발생: 참조 무결성 위배 (PARENT 테이블에 'B'가 없으므로 CHILD 테이블에 추가될 수 없음)
INSERT INTO PRACTICE.CHILD VALUES ('b', 'B');

INSERT INTO PRACTICE.PARENT VALUES ('B');
INSERT INTO PRACTICE.CHILD VALUES ('b', 'B');

-- 데이터 DELETE
-- 에러 발생: 참조 무결성 위배 (CHILD 테이블에 자식이 있으므로 PARENT 테이블에서 부모 데이터를 못 지움)
DELETE FROM PRACTICE.PARENT WHERE P_ID = 'A';

-- FK 옵션 변경
ALTER TABLE PRACTICE.CHILD DROP CONSTRAINT C_FK;

-- CASCADE 옵션: 부모 테이블에서 데이터 삭제 시에 자식 테이블에서도 데이터 삭제
ALTER TABLE PRACTICE.CHILD ADD CONSTRAINT C_FK FOREIGN KEY(P_ID) REFERENCES PRACTICE.PARENT(P_ID)
ON DELETE CASCADE; 

DELETE FROM PRACTICE.PARENT WHERE P_ID = 'A';

SELECT * FROM PRACTICE.CHILD;

-- 옵션 정리
--  1. CASCADE: PARENT 삭제 시 CHILD 같이 삭제
--  2. SET NULL: PARENT 삭제 시 CHILD의 해당 필드 NULL로 UPDATE 
--  3. SET DEFAULT: PARENT 삭제 시 CHILD의 해당 필드 DEFAULT 값으로 UPDATE
--  4. RESTRICT: CHILD 테이블에 PK 값이 없는 경우에만 PARENT 삭제
--  5. NO ACTION: 참조 무결성 제약조건을 위배하는 액션은 불가