CREATE TABLE EXAM_SCORE (

    이름      VARCHAR2(20),
    국어      NUMBER,
    영어      NUMBER,
    수학      NUMBER

);

INSERT INTO EXAM_SCORE VALUES ('김수현', 116, 77, 75);
INSERT INTO EXAM_SCORE VALUES ('박보검', 101, 69, 80);
INSERT INTO EXAM_SCORE VALUES ('아이유', 118, 62, 60);
INSERT INTO EXAM_SCORE VALUES ('김하늘', 96, 72, 70);
INSERT INTO EXAM_SCORE VALUES ('이효리', 103, 77, 55);
INSERT INTO EXAM_SCORE VALUES ('유재석', 78, 66, 61);
INSERT INTO EXAM_SCORE VALUES ('신동엽', 85, 72, 75);
INSERT INTO EXAM_SCORE VALUES ('서장훈', 99, 70, 53);
INSERT INTO EXAM_SCORE VALUES ('한혜진', 105, 75, 69);
INSERT INTO EXAM_SCORE VALUES ('김동률', 117, 68, 73);

SELECT * FROM EXAM_SCORE;

-- 테이블에 있는 성적으로 상대적으로 등급이 나눠짐
SELECT 이름,
       NTILE(8) OVER(ORDER BY 국어 DESC) 국어등급,
       국어,
       NTILE(8) OVER(ORDER BY 영어 DESC) 영어등급,
       영어,
       NTILE(8) OVER(ORDER BY 수학 DESC) 수학등급,
       수학
  FROM EXAM_SCORE;