ALTER SESSION SET STATISTICS_LEVEL = ALL;

SELECT * FROM HR.EMPLOYEES;

-- ORDER BY 이전에 WHERE 절이 먼저 실행되므로 SALARY 순이 아닌 무작위 10명이 출력됨
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
  FROM EMPLOYEES
 WHERE ROWNUM <= 10
 ORDER BY SALARY DESC;

-- 올바르게 SALARY 순으로 10명이 출력되는 쿼리
-- TOP-N 알고리즘이 작동되는지 확인 하기 위해 실행 계획에 COUNT STOPKEY가 있는지 확인
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY FROM (
    SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
      FROM EMPLOYEES
     ORDER BY SALARY DESC
)
WHERE ROWNUM <= 10;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(NULL, NULL, 'ALLSTATS LAST'));