CREATE TABLE CLOB_TEST (
    COL     CLOB -- 4000 Byte 이상의 데이터 삽입 가능 (VARCHAR는 최대 4000 Byte)
);

-- U : 랜덤한 4000 바이트의 대문자 생성
INSERT INTO CLOB_TEST VALUES (DBMS_RANDOM.STRING('U', 4000));

-- L : 랜덤한 4000 바이트의 소문자 생성
INSERT INTO CLOB_TEST VALUES (TO_CLOB(DBMS_RANDOM.STRING('U', 4000)) || DBMS_RANDOM.STRING('L', 4000));

SELECT * FROM CLOB_TEST;

SELECT * FROM CLOB_TEST WHERE COL LIKE 'A%';

SELECT LENGTH(COL), DBMS_LOB.GETLENGTH(COL), -- LENGTH 함수와 동일한 기능이지만 때에 따라 DBMS_LOB.GETLENGTH가 더 유리
       SUBSTR(COL, 1, 10), DBMS_LOB.SUBSTR(COL, 10, 1) -- SUBSTR 함수와 동일한 기능이지만 때에 따라 DBMS_LOB.SUBSTR가 더 유리
  FROM CLOB_TEST;