SELECT * FROM PRACTICE.IDOL_MEMBER;

-- 그룹별 생일 연도 빈도
SELECT GROUP_NAME,
       SUBSTR(BIRTHDAY, 1, 4) AS BIRTH_YEAR,
       COUNT(*)
  FROM PRACTICE.IDOL_MEMBER
 GROUP BY GROUP_NAME, SUBSTR(BIRTHDAY, 1, 4)
 ORDER BY GROUP_NAME;

SELECT SUBSTR(BIRTHDAY, 1, 4) AS BIRTH_YEAR,
       COUNT(CASE WHEN GROUP_NAME = 'BTS' THEN 1 END) AS "BTS",
       COUNT(CASE WHEN GROUP_NAME = '트와이스' THEN 1 END) AS "트와이스",
       COUNT(CASE WHEN GROUP_NAME = '아스트로' THEN 1 END) AS "아스트로",
       COUNT(CASE WHEN GROUP_NAME = '(여자)아이들' THEN 1 END) AS "(여자)아이들"
  FROM PRACTICE.IDOL_MEMBER
 GROUP BY SUBSTR(BIRTHDAY, 1, 4)
 ORDER BY BIRTH_YEAR;
 
-- row: 그룹 이름, column: 연도
SELECT * FROM (
        SELECT GROUP_NAME,
               SUBSTR(BIRTHDAY, 1, 4) AS BIRTH_YEAR
          FROM PRACTICE.IDOL_MEMBER
)
PIVOT(COUNT(*) FOR BIRTH_YEAR IN ('1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000'));
       
-- row: 연도, column: 그룹 이름
SELECT * FROM (
        SELECT GROUP_NAME,
               SUBSTR(BIRTHDAY, 1, 4) AS BIRTH_YEAR
          FROM PRACTICE.IDOL_MEMBER
)
 PIVOT(COUNT(*) FOR GROUP_NAME IN ('BTS', '트와이스', '아스트로', '(여자)아이들'))
 ORDER BY BIRTH_YEAR;

