SELECT * FROM STARBUCKS_ORDER;

-- 날짜별 
SELECT ORDER_DT, COUNT(*) FROM STARBUCKS_ORDER GROUP BY ORDER_DT ORDER BY ORDER_DT;
--      ROLLUP 함수: 마지막 행에 COUNT의 총합 표시
SELECT ORDER_DT, COUNT(*) FROM STARBUCKS_ORDER GROUP BY ROLLUP(ORDER_DT) ORDER BY ORDER_DT; 

-- 주문음료별
SELECT ORDER_ITEM, COUNT(*) FROM STARBUCKS_ORDER GROUP BY ORDER_ITEM;
--      ROLLUP
SELECT ORDER_ITEM, COUNT(*) FROM STARBUCKS_ORDER GROUP BY ROLLUP(ORDER_ITEM); 

-- 파트너별
SELECT REG_NAME, COUNT(*) FROM STARBUCKS_ORDER GROUP BY REG_NAME;
--      ROLLUP
SELECT REG_NAME, COUNT(*) FROM STARBUCKS_ORDER GROUP BY ROLLUP(REG_NAME); 

-- 2개 컬럼
SELECT ORDER_DT, ORDER_ITEM, COUNT(*) FROM STARBUCKS_ORDER GROUP BY ORDER_DT, ORDER_ITEM ORDER BY ORDER_DT;
--      ROLLUP: GROUP BY ORDER_DT, ORDER_ITEM
--              + GROUP BY ORDER_DT 
--              + 총 합계
SELECT ORDER_DT, ORDER_ITEM, COUNT(*) FROM STARBUCKS_ORDER GROUP BY ROLLUP(ORDER_DT, ORDER_ITEM) ORDER BY ORDER_DT;

-- 3개 컬럼
SELECT ORDER_DT, ORDER_ITEM, REG_NAME, COUNT(*) FROM STARBUCKS_ORDER GROUP BY ORDER_DT, ORDER_ITEM, REG_NAME ORDER BY ORDER_DT;
--      ROLLUP: GROUP BY ORDER_DT, ORDER_ITEM, REG_NAME
--              + GROUP BY ORDER_DT, ORDER_ITEM
--              + GROUP BY ORDER_DT
--              + 총 합계
SELECT ORDER_DT, ORDER_ITEM, REG_NAME, COUNT(*) FROM STARBUCKS_ORDER GROUP BY ROLLUP(ORDER_DT, ORDER_ITEM, REG_NAME) ORDER BY ORDER_DT;
--      ROLLUP: GROUP BY ORDER_DT, ORDER_ITEM, REG_NAME
--              + GROUP BY ORDER_DT
--              + 총 합계
SELECT ORDER_DT, ORDER_ITEM, REG_NAME, COUNT(*) FROM STARBUCKS_ORDER GROUP BY ROLLUP(ORDER_DT, (ORDER_ITEM, REG_NAME)) ORDER BY ORDER_DT;
