-- VIEW를 사용하는 이유
--  1. 공통 모듈을 생성해 VIEW를 참조하는 애플리케이션 단의 모든 쿼리를 수정하지 않고 VIEW만 수정
--  2. 복잡한 쿼리를 VIEW로 생성해 소스단의 쿼리가 간단해짐
--  3. 테이블의 전체 내용이 아닌 필요한 컬럼들로만 VIEW를 생성해 다른 사람들에게 제공하므로써 보안을 높임

SELECT * FROM PRACTICE.IDOL_GROUP;

-- BTS 회사와 그룹이름 데이터를 가진 VIEW 생성
CREATE OR REPLACE VIEW PRACTICE.V1_IDOL AS
SELECT COMPANY, GROUP_NAME FROM PRACTICE.IDOL_GROUP WHERE GROUP_NAME = 'BTS';

SELECT * FROM PRACTICE.V1_IDOL;

-- BTS 멤버 정보 데이터를 가진 VIEW 생성
CREATE OR REPLACE VIEW PRACTICE.V2_IDOL AS
SELECT A.COMPANY, A.GROUP_NAME, B.MEMBER_NAME, B.REAL_NAME
  FROM PRACTICE.IDOL_GROUP A,
       PRACTICE.IDOL_MEMBER B
 WHERE A.GROUP_NAME = B.GROUP_NAME
   AND A.GROUP_NAME = 'BTS';
   
SELECT * FROM PRACTICE.V2_IDOL;

-- VIEW 삭제
DROP VIEW PRACTICE.V1_IDOL;
DROP VIEW PRACTICE.V2_IDOL;